#!/bin/sh
NAME="Music Uploader Service"

start() {
    echo "Starting $NAME"
    exec pnpm start --silent -C /home/ultramixerman/home/Development/musicUploader &
    RETVAL=$?
}

stop() {
    echo "Shutting down $NAME"
    exec pnpm stop --silent -C /home/ultramixerman/home/Development/musicUploader &
    RETVAL=$?
}

restart() {
    echo "Restarting $NAME"
    stop
    start
}

status() {
    echo "Status for $NAME:"
    output=$(curl -s -H -m 5 http://127.0.0.1:8200/status)
    if [ "$output" = "SUCCESS" ]; then
        echo "RUNNING"
    else
        echo "FAILED"
    fi
    RETVAL=$?
}

case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        restart
    ;;
    status)
        status
    ;;
esac

exit $RETVAL