#!/bin/sh

commit_id=$1
curl -sSL --insecure "https://update.code.visualstudio.com/commit:${commit_id}/server-linux-x64/stable" -o vscode-server-linux-x64.tar.gz
tar zxvf ./vscode-server-linux-x64.tar.gz -C ~/.vscode-server/bin/${commit_id} --strip 1
